/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_app;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author marcos
 */

public class Board extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final Image [] hola = new Image [10];
    
    public Board() {
        initBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initBoard() {
        setLayout(new BorderLayout());
        
        
        loadImage();

        setPreferredSize(new Dimension(250, 300));        
    }
    
    private void loadImage() {
        ImageIcon ii = new ImageIcon(getClass().getResource("/my_app/resources/Suelo.png"));
        hola[0] = ii.getImage();
        ii = new ImageIcon(getClass().getResource("/my_app/resources/Robot.png"));
        hola[1] = ii.getImage();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        for(int i=0;i<=10;i++)
            for(int j=0;j<=10;j++)
                g.drawImage(hola[0], i*25, j*25, null);
        g.drawImage(hola[1], 0, 10*25, null);
        //Sustituir por valores obtenidos del teclado
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
